name: Process Text File

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  process-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read and process text file
        id: process
        run: |
          # Ensure the input file exists
          INPUT_FILE="input.txt"  # Change this to your text file name
          
          if [ -f "$INPUT_FILE" ]; then
            echo "Processing $INPUT_FILE..."
            # Example: Count lines in the file
            LINE_COUNT=$(wc -l < "$INPUT_FILE")
            echo "Line count: $LINE_COUNT"
            echo "line_count=$LINE_COUNT" >> $GITHUB_ENV
          else
            echo "File not found!"
            exit 1
          fi

      - name: Use the processed output
        run: |
          echo "The line count from the previous step is ${{ env.line_count }}"
